const  CURRENT_SENSOR_ID = 1, CURRENT_SENSOR_NAME = "current", RELAY_ID = 2, RELAY_NAME = "relay";

module.exports.CURRENT_SENSOR_ID = CURRENT_SENSOR_ID;
module.exports.CURRENT_SENSOR_NAME = CURRENT_SENSOR_NAME;
module.exports.RELAY_ID = RELAY_ID;
module.exports.RELAY_NAME = RELAY_NAME;